name: 'red-cat-pictures-dev'
services:
  app:
    build:
      context: .
      args:
        SITE_URL: https://algorithm-personal-being-realized.trycloudflare.com
        CDN_URL: https://fin-quarters-shared-flexibility.trycloudflare.com/media
    restart: on-failure:3
    env_file:
      - .env.prod
    volumes:
      - static:/app/static
      - data:/app/.data
    ports:
      - 4300:3000
    # runtime: nvidia # Enable NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    depends_on:
      - browserless
  browserless:
    image: ghcr.io/browserless/chromium:latest
    restart: on-failure:3
    user: root
    volumes:
      - data:/usr/src/app/user-data-dir
    environment:
      - CORS=true
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://0.0.0.0:3000/ || exit 1']
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 10s
  # directus:
  #   image: directus/directus:11
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     - ./directus/database:/directus/database
  #     - ./directus/uploads:/directus/uploads
  #     - ./directus/extensions:/directus/extensions
  #   environment:
  #     SECRET: 'replace-with-secure-random-value'
  #     ADMIN_EMAIL: 'admin@example.com'
  #     ADMIN_PASSWORD: 'd1r3ctu5'
  #     DB_CLIENT: 'sqlite3'
  #     DB_FILENAME: '/directus/database/data.db'
  #     WEBSOCKETS_ENABLED: 'true'

volumes:
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static

  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
