version: '3.9'
services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    env_file:
      - .env
    volumes:
      - backend-data:/cloudreve/data
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    restart: 'on-failure:3'
    deploy:
      resources:
        limits:
          cpus: '1'

  postgres:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - database-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U documenso']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - internal
    restart: 'on-failure:3'

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - internal
    restart: 'on-failure:3'

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/data
  database-postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/postgres
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/redis

networks:
  internal:
    driver: bridge
